# ESTATÍSTICA 
## Material Consolidado de INFERÊNCIA

In [3]:
import numpy as np
from math import sqrt, exp
from statistics import stdev

In [4]:
from scipy.stats import binom, poisson

In [5]:
from stats import binomial as bi
from stats import exponencial as xp
from stats import poisson as po
from stats import normal as nm
from stats import inferencia as inf
from stats import hipoteses as hip

# INFERENCIA

### Amostra para cálculos intermediários

In [36]:
amostra1 = np.array([11.6, 8.8, 9.9, 9.5, 11.6, 9.1, 10.6, 10.8, 13.4, 10.6, 10.5, 11.4])
print(f"Média: {round(amostra1.mean(),4)}")
print(f"Desvio padrão: {round(amostra1.std(ddof=1),4)}")
print(f"Tamanho: {len(amostra1)}")

amostra2 = np.array([8.1, 7.9, 6.8, 7.8, 7.6, 7.9, 5.7, 8.4, 8 , 9.5, 8, 6.8])
print(f"Média: {round(amostra2.mean(),4)}")
print(f"Desvio padrão: {round(amostra2.std(ddof=1),4)}")
print(f"Tamanho: {len(amostra2)}")


Média: 10.65
Desvio padrão: 1.2681
Tamanho: 12
Média: 7.7083
Desvio padrão: 0.9434
Tamanho: 12


## MÉDIA(z) - Intervalo de Confiança

In [27]:
sigma = 1.5
n = 20
z = 1.64
e = inf.media_margem_erro(z, sigma, n)
# N = ?
med = 22.9
inf.print_intervalo_confianca(med, e)

Intervalo confiança: [22.3499 ; 23.4501]


## MÉDIA(z) - Tamanho da amostra

In [33]:
sigma = sqrt(0.1764)
z =2.57
e = 0.05
# N=386
n = inf.media_tamanho_amostra(z, sigma, e)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 467.0000


## MÉDIA(t) - Intervalo de confiança

In [26]:
n = 29
gl = n-1 # grau de liberdade
alpha = 0.05
med = 30
s = 7
t = 2.048
e = inf.media_margem_erro(t, s, n)
inf.print_intervalo_confianca(med, e)

Intervalo confiança: [27.3379 ; 32.6621]


## MÉDIA(t) - Tamanho da Amostra

In [25]:
n = 16
gl = n-1 # grau de liberdade
alpha = 0.02
med = 330
s = 40
t = 2.602
e = 26.02
n = inf.media_tamanho_amostra(t, s, e)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 16.0000


## PROPORÇÃO(z) - Intervalo de confiança

In [28]:
z = 1.96
n = 180
x = 18 
pa = x/n    
# N = ?
e = inf.prop_margem_erro(z, pa, n)
inf.print_intervalo_confianca(pa, e)

Intervalo confiança: [0.0562 ; 0.1438]


## PROPORÇÃO(z) - Tamanho da Amostra

In [30]:
z = 1.64
pa = 0.5
e = 0.025
# N = 1286
n = inf.prop_tamanho_amostra(z, pa, e)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 1076.0000


## TESTES DE HIPÓTESES

## Teste t para uma média (desvio desconhecido)

In [12]:
# H0: med <= 7 
# Ha: med > 7 

xhat = 7.25
mu0 = 7
s = 1.052
alpha = 0.05
n = 27
tt = hip.media_testet(xhat, mu0, s, n)
tt

1.2348

## Teste t para duas médias (amostras dependentes)

In [47]:
x = np.array([16, 	15, 	11, 	20, 	19, 	14, 	13, 	15, 	14, 	16])
y = np.array([13, 	13 ,	12 ,	16 ,	16 ,	11, 	10, 	15, 	9, 	16])
di = x - y
print(x)
print
print(y)
print(di)

[16 15 11 20 19 14 13 15 14 16]
[13 13 12 16 16 11 10 15  9 16]
[ 3  2 -1  4  3  3  3  0  5  0]


In [48]:
n = len(di)
di_med = di.mean()
di_std = di.std(ddof = 1)
print("n: {:6} Média di: {:10.4f} Desvio Padrão di: {:10.4f}".format(n, di_med, di_std))

n:     10 Média di:     2.2000 Desvio Padrão di:     1.9322


In [49]:
tp = hip.media_testet_amostras_dependentes(di_med, di_std, n)
tp
# O valor p será a 2 X P(tp)

3.6006

## Teste F para comparação de duas variâncias

In [45]:
n1 = 28
n2 = 22
var1 = 150**2
var2 = 125**2
F = var1/var2
FL = 1/2.237
FR = 2.308
print("F: {:6.4} FL: {:6.4}  FR: {:6.4} ".format(F, FL, FR))

F:   1.44 FL:  0.447  FR:  2.308 


## Teste t para duas médias (amostras independentes)

#### Populações Homocedásticas

In [65]:
n1 = 26
n2 = 26 
var1 = 0.6**2
var2 = 0.7**2
x1 = 2.8
x2 = 2.3
t = hip.media_testet_amostras_independentes(x1, x2, n1, n2, var1, var2, True)
gl = n1 + n2 -2
print("Graus de liberdade: {}".format(gl))
print("t = {:6.4f}".format(t))
# O valor p será a 2 X P(tp)

Graus de liberdade: 50
t = 2.7653


#### Populações Heterocedásticas

In [64]:
n1 = 9
n2 = 9 
var1 = 449.33
var2 = 2391.5
x1 = 227
x2 = 449.33
t = hip.media_testet_amostras_independentes(x1, x2, n1, n2, var1, var2, False)
gl = 8
print("Graus de liberdade: {}".format(gl))
print("t = {:6.4f}".format(t))
# O valor p será a 2 X P(tp)

Graus de liberdade: 8
t = -12.5140
