## ESTATÍSTICA 
## Material Consolidado

In [11]:
import numpy as np
from math import sqrt
from statistics import stdev

In [12]:
from stats import binomial as bi
from stats import exponencial as xp
from stats import poisson as po
from stats import normal as nm
from stats import inferencia as inf
from stats import hipoteses as hip

## TESTES DE HIPÓTESES

## Teste t para duas médias (amostras dependentes)

In [13]:
x = np.array([200, 174, 198, 170, 179])
y = np.array([191, 170, 177, 167, 159])
di = x - y
print(x)
print
print(y)
print(di)

[200 174 198 170 179]
[191 170 177 167 159]
[ 9  4 21  3 20]


In [14]:
n = len(di)
di_med = di.mean()
di_std = di.std(ddof = 1)
print("n: {:6} Média di: {:10.4f} Desvio Padrão di: {:10.4f}".format(n, di_med, di_std))

n:      5 Média di:    11.4000 Desvio Padrão di:     8.6197


In [15]:
tp = hip.media_testet_amostras_dependentes(di_med, di_std, n)
tp

2.9573

## Teste F para comparação de duas variâncias

In [16]:
n1 = 25
n2 = 30
s1 = 1.3623**2
s2 = 2.8876**2
F = s1/s2
FL = 1/2.209
FR = 2.154
print("F: {:6.4} FL: {:6.4}  FR: {:6.4} ".format(F, FL, FR))

F: 0.2226 FL: 0.4527  FR:  2.154 


## Teste t para duas médias (amostras independentes)

#### Populações Homocedásticas

In [17]:
n1 = 14
n2 = 10 
s1 = 16**2
s2 = 15**2
x1 = 121
x2 = 112
t = hip.media_testet_amostras_independentes(x1, x2, n1, n2, s1, s2, True)
gl = n1 + n2 -2
print("Graus de liberdade: {}".format(gl))
print("t = {:6.4f}".format(t))

Graus de liberdade: 22
t = 1.3935


#### Populações Heterocedásticas

In [18]:
n1 = 36
n2 = 39 
s1 = 0.00020
s2 = 0.00135
x1 = 0.81
x2 = 0.78
t = hip.media_testet_amostras_independentes(x1, x2, n1, n2, s1, s2, False)
gl = 35
print("Graus de liberdade: {}".format(gl))
print("t = {:6.4f}".format(t))

Graus de liberdade: 35
t = 4.7333
