## ESTATÍSTICA 
## Material Consolidado

In [37]:
import numpy as np
from math import sqrt, exp
from statistics import stdev

In [53]:
from scipy.stats import binom, poisson

In [39]:
from stats import binomial as bi
from stats import exponencial as xp
from stats import poisson as po
from stats import normal as nm
from stats import inferencia as inf
from stats import hipoteses as hip

## MODELOS PROBABILÍSTICOS - VARIÁVEIS DISCRETAS

## Distribuição Binomial

In [62]:
n = 10
p = 0.3
prob = binom(n,p)
result = lambda n, p : print(f"Média: {binom.mean(n, p)}, Variância: {binom.var(n, p)}, Desvio: {binom.std(n, p)}")
print(result(n, p))
print(prob.pmf(3)+prob.pmf(4)+prob.pmf(5))
print(prob.cdf(5)-prob.cdf(2)) # conferir

Média: 3.0, Variância: 2.0999999999999996, Desvio: 1.4491376746189437
None
0.5698682262000003
0.5698682261999999


## Distribuição de Poisson

In [54]:
mu = 5*8 # por hora
prob = poisson(mu)
prob.pmf(50)

0.01770701755263633

## MODELOS PROBABILÍSTICOS - VARIÁVES CONTÍNUAS

## Distribuição Exponencial

In [65]:
med = lambda alpha : 1 / alpha
var = lambda alpha : 1 / (alpha ** 2)
result = lambda alpha : print(f"Média: {med(alpha)}, Variância: {var(alpha)}")
prob = lambda a, b, alpha : exp(-alpha*a)-exp(-alpha*b)

In [66]:
alpha = 3
a = 0
b = 1
prob(a, b, alpha)

0.950212931632136

## INFERENCIA

## Tamanho da amostra  - MÉDIA(população infinita)

In [41]:
sigma = sqrt(0.1764)
alpha = 0.01 # 99%
z =2.57
e = 0.05
n = inf.media_tamanho_amostra(z, sigma, e)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 467.0000


## Tamanho da amostra  - MÉDIA(população finita)

In [42]:
sigma = 7000 
z = 1.64
e = 600
n = inf.media_tamanho_amostra(z, sigma, e)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 367.0000


## Tamanho da amostra - PROPORÇÃO (população infinita)

In [43]:
z = 1.64
pa = 0.5
e = 0.025
n = inf.prop_tamanho_amostra(z, pa, e)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 1076.0000


## Tamanho da amostra - PROPORÇÃO (população finita)

In [44]:
N = 1286
z = 1.64
pa = 0.5
e = 0.04
n = inf.prop_tamanho_amostra(z, pa, e, N)
print("Tamanho recomendado da amostra: {:6.4f}".format(n))

Tamanho recomendado da amostra: 317.0000


## TESTES DE HIPÓTESES

## Teste t para uma média (desvio desconhecido)

In [45]:
# H0: med <= 7 
# Ha: med > 7 

xhat = 7.25
mu0 = 7
s = 1.052
alpha = 0.05
n = 27
tt = hip.media_testet(xhat, mu0, s, n)
tt

1.2348

## Teste t para duas médias (amostras dependentes)

In [46]:
x = np.array([16, 15, 11, 20, 19, 14, 13, 15, 14, 16])
y = np.array([13, 13, 12, 16, 16, 11, 10, 15, 9, 16])
di = x - y
print(x)
print
print(y)
print(di)

[16 15 11 20 19 14 13 15 14 16]
[13 13 12 16 16 11 10 15  9 16]
[ 3  2 -1  4  3  3  3  0  5  0]


In [47]:
n = len(di)
di_med = di.mean()
di_std = di.std(ddof = 1)
print("n: {:6} Média di: {:10.4f} Desvio Padrão di: {:10.4f}".format(n, di_med, di_std))

n:     10 Média di:     2.2000 Desvio Padrão di:     1.9322


In [48]:
tp = hip.media_testet_amostras_dependentes(di_med, di_std, n)
tp

3.6006

## Teste F para comparação de duas variâncias

In [49]:
n1 = 28
n2 = 22
s1 = 150**2
s2 = 125**2
F = s1/s2
FL = 1/2.201
FR = 2.272
print("F: {:6.4} FL: {:6.4}  FR: {:6.4} ".format(F, FL, FR))

F:   1.44 FL: 0.4543  FR:  2.272 


## Teste t para duas médias (amostras independentes)

#### Populações Homocedásticas

In [50]:
n1 = 28
n2 = 22 
s1 = 150**2
s2 = 125**2
x1 = 1025
x2 = 910
t = hip.media_testet_amostras_independentes(x1, x2, n1, n2, s1, s2, True)
gl = n1 + n2 -2
print("Graus de liberdade: {}".format(gl))
print("t = {:6.4f}".format(t))

Graus de liberdade: 48
t = 2.8912


#### Populações Heterocedásticas

In [51]:
n1 = 28
n2 = 22 
s1 = 150**2
s2 = 125**2
x1 = 0.81
x2 = 0.78
t = hip.media_testet_amostras_independentes(x1, x2, n1, n2, s1, s2, False)
gl = 35
print("Graus de liberdade: {}".format(gl))
print("t = {:6.4f}".format(t))

Graus de liberdade: 35
t = 0.0008
